---
# all, none, or list of linter keys
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - apm_modules
  - node_modules
APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
IGNORE_GITIGNORED_FILES: true
JAVASCRIPT_DEFAULT_STYLE: prettier
JSON_PRETTIER_PRE_COMMANDS:
  - command: npm i -g bun
    continue_if_failed: false
    cwd: workspace
    secured_env: true
    tag: default
  - command: bun ci
    continue_if_failed: true
    cwd: workspace
    secured_env: true
    tag: default
MARKDOWN_DEFAULT_STYLE: rumdl
PYTHON_DEFAULT_STYLE: ruff
REPOSITORY_KINGFISHER_ARGUMENTS: --exclude node_modules --exclude apm_modules
SHOW_ELAPSED_TIME: true
TYPESCRIPT_DEFAULT_STYLE: prettier
YAML_PRETTIER_PRE_COMMANDS:
  - command: npm i -g bun
    continue_if_failed: false
    cwd: workspace
    secured_env: true
    tag: default
  - command: bun ci
    continue_if_failed: true
    cwd: workspace
    secured_env: true
    tag: default
