---
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}
jobs:
  cog_check_job:
    name: Conventional Commits Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Conventional commits check
        uses: cocogitto/cocogitto-action@9a9fe03b31c47444290c0d7f9b1ee1b44ee13f20 # v4.1.0
        with:
          command: check
name: Conventional Commits Check
on: # yamllint disable-line rule:truthy
  pull_request:
  push:
permissions: {}
